[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating secrets for Veracruz's Shamir secret sharing example."
edition = "2018"
name = "shamir-secret-sharing"
version = "0.3.0"

[dependencies]
hex = "0.4"
rand = "0.8.3"
structopt = { version = "0.3", features = ["wrap_help"] }
