[package]
authors = ["The Veracruz Development Team"]
description = "Remove all non-prime numbers from the number-set"
name = "keep-primes"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
