# Authors: The Veracruz Development Team
# CI for Veracruz project.
#
image: "$DOCKER_IMAGE_PATH"

variables:
  CARGO_HOME: $VERACRUZ_PATH/.cargo
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1

before_script:
    ################################################# 
    ## project specific setting 
    #################################################
    # return the veracruz dir
    - cd $VERACRUZ_PATH

stages:
    - sdk-build
    - enclave-build
    - test

cache: &global_cache
    key: GLOBAL_CACHE
    paths:
        - "$VERACRUZ_PATH/**/target/**"
        - "$VERACRUZ_PATH/.cargo/**"
        - "$VERACRUZ_PATH/test-collateral/**"
    policy: pull-push

build:sdk:
    stage: sdk-build
    script:
        - make clean
        - make sdk
    cache:
        <<: *global_cache
        key: SDK
        policy: push
