version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: trustzone
      buildspec: trustzone_buildspec.yml
      ignore-failure: false
    - identifier: sgx_build
      buildspec: sgx_buildspec.yml
      ignore-failure: false
