# Clippy configuration file for the Veracruz project.
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT AND LICENSING
#
# See the `LICENSE_MIT.markdown` file in the Veracruz repository root
# directory for copyright and licensing information.

