#!/usr/bin/env python3

import json
import hashlib

def main(in_json, out_h, out_c):
    with open(in_json) as f:
        policy_raw = f.read()
        policy_hash = hashlib.sha256(policy_raw.encode('utf-8')).hexdigest()
        policy = json.loads(policy_raw)

    print('Generating %s for policy %s' % (out_h, policy_hash))
    with open(out_h, 'w') as f:
        _write = f.write
        def write(s='', **args):
            _write(s % args)
        def writeln(s='', **args):
            _write(s % args)
            _write('\n')
        f.write = write
        f.writeln = writeln

        f.writeln('//// AUTOGENERATED ////')
        f.writeln('#ifndef VERACRUZ_POLICY_H')
        f.writeln('#define VERACRUZ_POLICY_H')
        f.writeln()
        f.writeln('#include <stdint.h>')
        f.writeln()
        f.writeln('extern uint8_t _veracruz_policy_raw[];')
        f.writeln()
        f.writeln('#define VERACRUZ_POLICY_HASH "%(hash)s"',
            hash=policy_hash)
        f.writeln('#define VERACRUZ_POLICY_RAW _veracruz_policy_raw')
        f.writeln()
        f.writeln('#endif')

    print('Generating %s for policy %s' % (out_c, policy_hash))
    with open(out_c, 'w') as f:
        _write = f.write
        def write(s='', **args):
            _write(s % args)
        def writeln(s='', **args):
            _write(s % args)
            _write('\n')
        f.write = write
        f.writeln = writeln

        f.writeln('//// AUTOGENERATED ////')
        f.writeln()
        f.writeln('#include <stdint.h>')
        f.writeln()
        f.writeln('uint8_t _veracruz_policy_raw[] = {')
        for i in range(0, len(policy_raw), 8):
            f.writeln('    %(raw)s',
                raw=' '.join('0x%02x,' % ord(x)
                    for x in policy_raw[i : min(i+8, len(policy_raw))]))
        f.writeln('};')

if __name__ == "__main__":
    import sys
    main(*sys.argv[1:])
