//// AUTOGENERATED ////
#ifndef VERACRUZ_POLICY_H
#define VERACRUZ_POLICY_H

#include <stdint.h>

extern uint8_t _veracruz_policy_raw[];

#define VERACRUZ_POLICY_HASH "2713d3d5a1b4570049f971cc8ca53f95cd4010710ba09f6622baefca127281ff"
#define VERACRUZ_POLICY_RAW _veracruz_policy_raw

#endif
