[package]
name = "string-generator"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A utility for generating synthetic strings for use with various examples (e.g. `string-edit-distance`)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
serde = { version = "1.0.103", features = ["derive"] }
clap = "2.33"
bitflags = "=1.2.1"
