# This makefile is used to generate the non-secure server for the AWS Nitro
# Enclave for the Veracruz root enclave
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE.markdown` file in the Veracruz root directory for licensing
# and copyright information.

.PHONY:
all:
	cargo build

.PHONY:
fmt:
	cargo fmt

.PHONY:
clean:
	cargo clean
