[package]
authors = ["The Veracruz Development Team"]
description = "Computes the sum of values associated with keys k_i appearing in set A where k_i also appears in set B."
edition = "2018"
name = "private-set-intersection-sum"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
pinecone = { git = "https://github.com/egrimley-arm/pinecone", features = ["use-std"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
