# Makefile to build freestanding-chihuahua
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE.markdown` file in the Veracruz root directory for licensing
# and copyright information.

.PHONY: all clean fmt

all:
	cargo build --release

fmt:
	cargo fmt

clean:
	cargo clean
