[package]
authors = ["The Veracruz Development Team"]
description = "Client code for provisioning secrets into, and otherwise interacting with, the trusted Veracruz runtime"
edition = "2018"
name = "veracruz-client"
version = "0.3.0"

[[bin]]
name = "veracruz-client"
path = "src/cli.rs"

[features]
linux = []
nitro = [
  "mbedtls/monitor_getrandom",
]

[dependencies]
anyhow = "1"
bincode = { version = "1.2.1", default-features = false }
clap = { version = "4", features = ["derive"] }
env_logger = { version = "0.10.0" }
err-derive = "0.2"
hex = "0.4.2"
log = "0.4.13"
mbedtls = { path = "../third-party/rust-mbedtls/mbedtls", default-features = false, features = ["std", "aesni", "padlock", "tls13"] }
policy-utils = { path = "../policy-utils", features = ["std"] }
rand = "0.8.3"
serde_json = "1.0"
transport-protocol = { path = "../transport-protocol" }
veracruz-utils = { path = "../veracruz-utils", features = ["std"] }
