[package]
name = "tabasco-cli"
version = "0.1.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = """\
    Command-line interface for Tabasco, the REST frontend \
    for Veracruz's proxy attestation service."""
autobins = false

# this is the only way to change the default binary name
[[bin]]
name = "tabasco"
path = "src/main.rs"

[features]
sgx = ["sgx_ucrypto", "sgx_urts", "sgx_types", "veracruz-utils/std", "tabasco/sgx"]
tz = ["veracruz-utils/tz", "tabasco/psa"]

[dependencies]
veracruz-utils = {path = "../veracruz-utils", features=["std"] }
tabasco = { path = "../tabasco" }
structopt = { version="0.3", features=["wrap_help"] }
log = "0.4"
env_logger = "0.7"
ring = "0.16"
hex = "0.4"
actix-rt = "1.0.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
sgx_types = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
