[package]
authors = ["The Veracruz Development Team"]
description = "A utility for geneting synthetic datasets for use with the `private-set-intersection` example."
edition = "2018"
name = "private-set-intersection-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "=1.2.1"
clap = "2.33"
csv = "1.0"
pinecone = { git = "https://github.com/egrimley-arm/pinecone.git", branch = "veracruz" }
serde = { version = "1.0.103", features = ["derive"] }
