[package]
authors = ["The Veracruz Development Team"]
description = "Computes the moving-average-convergence-divergence (MACD) metric of a dataset.  This is often used in financial mathematics."
edition = "2018"
name = "moving-average-convergence-divergence"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
pinecone = { git = "https://github.com/veracruz-project/pinecone.git", branch = "veracruz", features = ["use-std"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
