[package]
authors = ["The Veracruz Development Team"]
name = "remove-five-seven-multiples"
description = "Remove all number that are multiples of 5 or 7"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
