# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root directory for licensing
# and copyright information.

[package]
name = "runtime-manager-types"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"

[dependencies]
serde = { version = "*", default-features = false, features = [ "alloc", "derive"] }
libc = { path = "../../../deps/libc" }
