[package]
authors = ["The Veracruz Development Team"]
description = "A freestanding WASM execution engine implementing the Veracruz ABI for offline development and testing."
edition = "2018"
name = "freestanding-execution-engine"
version = "0.3.0"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10.0"
execution-engine = { path = "../execution-engine", features = ["std"] }
log = "0.4.13"
postcard = "1.0.0"
policy-utils = { path = "../policy-utils", features = ["std"] }
wasi-types = { path = "../third-party/wasi-types" }

[[bin]]
name = "freestanding-execution-engine"
path = "src/main.rs"
