[package]
name = "private-set-intersection"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Computes the intersection of two input sets."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "*"
serde = { version = "1.0.3", features = ["derive"] }
libveracruz = {path = "../../libveracruz"}

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

