[package]
authors = ["The Veracruz Development Team"]
build = "build.rs"
description = "Veracruz protocol message wire-format parsing and serialization code for the trusted Veracruz runtime"
edition = "2018"
name = "transport-protocol"
version = "0.3.0"

[dependencies]
anyhow = "1"
err-derive = "0.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "=3.2.0"
home = "=0.5.5"
