[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"
edition = "2018"
name = "veracruz-utils"
version = "0.3.0"

[features]
linux = [
  "platform-services/std"
]
nitro = [
  "mbedtls/monitor_getrandom",
  "platform-services/nitro"
]
std = [
  "chrono",
  "platform-services/std"
]

[dependencies]
anyhow = "1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"], optional = true }
err-derive = "0.2"
mbedtls = { path = "../third-party/rust-mbedtls/mbedtls", default-features = false, features = ["std", "aesni", "padlock", "tls13"] }
platform-services = { path = "../platform-services", optional = true }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
serde = { version = "1.0.185", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
uuid = { version = "1.1.2", features = ["serde"] }
