# workspaces/nitro-host/Cargo.toml:
# Workspace for untrusted Nitro services and tests
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE_MIT.markdown` file in the Veracruz root director for licensing
# and copyright information.

cargo-features = ["resolver"]

[workspace]
exclude = [
  "crates/third-party/rust-mbedtls",
  "crates/third-party/wasmi",
]
members = [
  "crates/veracruz-client",
  "crates/sev-veracruz-server",
  "crates/tests",
  "src/sev-host",
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
