linux-aarch64:
	cargo build --release --target aarch64-unknown-linux-gnu

linux-x64:
	cargo build --release --target x86_64-unknown-linux-gnu

linux:
	cargo build --release

fmt:
	cargo fmt

clean:
	cargo clean
	$(RM) -f Cargo.lock
