[package]
authors = ["The Veracruz Development Team"]
description = "Logistic regression example, using the Rust rusty-machine ML library."
edition = "2018"
name = "logistic-regression"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
postcard = { version = "0.7.2", features = [ "alloc", "use-std" ] }
rusty-machine = "0.5.4"
serde = { version = "1.0.3", features = ["derive"] }
