[package]
authors = ["The Veracruz Development Team"]
description = "Common IO-related code used by multiple Veracruz components."
edition = "2018"
name = "io-utils"
version = "0.3.0"

[features]
linux = ["bincode"]
nitro = ["nix"]

[dependencies]
anyhow = "1"
base64 = { version = "0.13.0" }
bincode = { version = "1.2.1", default-features = false, optional = true }
byteorder = { version = "1.4.3" }
err-derive = "0.2"
log = "0.4.13"
nix = { version = "0.26", optional = true }
serde = { version = "1.0.185", features = ["derive"] }
