cargo run apple_prices.csv 40
cargo run apple_prices.csv 60
cargo run apple_prices.csv 80
cargo run apple_prices.csv 100
cargo run apple_prices.csv 120
cargo run apple_prices.csv 140
cargo run apple_prices.csv 160
cargo run apple_prices.csv 180
cargo run apple_prices.csv 200
cargo run apple_prices.csv 220
cargo run apple_prices.csv 240
cargo run apple_prices.csv 260
cargo run apple_prices.csv 280
cargo run apple_prices.csv 300
cargo run apple_prices.csv 320
cargo run apple_prices.csv 340
cargo run apple_prices.csv 360
cargo run apple_prices.csv 380
cargo run apple_prices.csv 400
cargo run apple_prices.csv 420
cargo run apple_prices.csv 440
cargo run apple_prices.csv 460
cargo run apple_prices.csv 480
cargo run apple_prices.csv 500
cargo run apple_prices.csv 520
cargo run apple_prices.csv 540
cargo run apple_prices.csv 560
cargo run apple_prices.csv 580
cargo run apple_prices.csv 600
cargo run apple_prices.csv 620
cargo run apple_prices.csv 640
cargo run apple_prices.csv 660
cargo run apple_prices.csv 680
cargo run apple_prices.csv 700
cargo run apple_prices.csv 720
cargo run apple_prices.csv 740
cargo run apple_prices.csv 760
cargo run apple_prices.csv 780
cargo run apple_prices.csv 800
cargo run apple_prices.csv 820
cargo run apple_prices.csv 840
cargo run apple_prices.csv 860
cargo run apple_prices.csv 880
cargo run apple_prices.csv 900
cargo run apple_prices.csv 920
cargo run apple_prices.csv 940
cargo run apple_prices.csv 960
cargo run apple_prices.csv 980
cargo run apple_prices.csv 1000
