# docker image for remote CI.
# Downloads additional Rust toolchains / components
#
# AUTHORS
#
# The Veracruz Development Team.
#
# COPYRIGHT
#
# See the `LICENSE.markdown` file in the Veracruz root directory for licensing
# and copyright information.
#
# NOTE: We try to follow the guide in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
#       Each RUN contains a bundle of steps, which reduces the cache.

ARG VERSION="latest"

FROM veracruz/ci-base:${VERSION} as final

ARG ARCH=x86_64
ARG ICECAP_RUST_VERSION=nightly-2021-08-25

RUN rustup target add ${ARCH}-unknown-linux-musl wasm32-wasi && \
    rustup toolchain install ${ICECAP_RUST_VERSION}  --target aarch64-unknown-linux-gnu && \
    rustup component add --toolchain ${ICECAP_RUST_VERSION} rustfmt rust-src

WORKDIR /work
