[package]
name = "nop"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "The NOP example: does not do anything."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libveracruz = {path = "../../libveracruz"}

[profile.release]
opt-level = 3
codegen-units = 1

