[package]
authors = ["The Veracruz Development Team"]
description = "WASM execution engine for the trusted Veracruz runtime"
edition = "2018"
name = "execution-engine"
version = "0.3.0"

[features]
default = []
nitro = [
  "mbedtls/monitor_getrandom",
  "platform-services/nitro",
]
std = [
  "nix",
  "platform-services/std",
]

[dependencies]
log = "0.4.13"
anyhow = "1"
cfg-if = "1"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
mbedtls = { path = "../third-party/rust-mbedtls/mbedtls", default-features = false, features = ["std", "aesni", "padlock", "tls13"] }
nix = { version = "0.26", optional = true }
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
platform-services = { path = "../platform-services" }
policy-utils = { path = "../policy-utils", features = ["std"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0"
wasi-types = { path = "../third-party/wasi-types" }
wasmtime = "11"
wasmtime-wasi = "11"

[lib]
name = "execution_engine"
path = "./src/lib.rs"
