[package]
authors = ["The Veracruz Development Team"]
description = "Reconstruct a secret using Shamir's secret sharing scheme"
edition = "2018"
name = "shamir-secret-sharing"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
