[package]
authors = ["The Veracruz Development Team"]
description = "A Rust reimplementation of the winning logistic regression entry in the IDASH 2017 competition."
edition = "2018"
name = "idash2017-logistic-regression"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
pinecone = { git = "https://github.com/egrimley-arm/pinecone", features = ["use-std"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
