[package]
authors = ["The Veracruz Development Team"]
description = "Triangulation via audio events"
edition = "2018"
name = "audio-event-triangulation"
version = "0.3.0"

[dependencies]
anyhow = "1.0.14"
thiserror = "1.0.26"
