[package]
authors = ["The Veracruz Development Team"]
description = "An abstraction layer for various isolation technologies.  Exposes a uniform interface to the various Veracruz libraries for accessing hardware/TEE-specific functionality that differs between isolation technology."
edition = "2018"
name = "platform-services"
version = "0.3.0"

[features]
std = ["getrandom"]
nitro = ["nsm_api"]

[dependencies]
getrandom = { version = "0.2", optional = true }
nix = "0.26"
nsm_api = { package = "aws-nitro-enclaves-nsm-api", version = "0.3.0", optional = true }
